#!/usr/bin/env node
// Pillcrow fork: write one client's Wrangler config, so several installs can share one
// Cloudflare account. Each gets its own Worker, D1, R2 bucket, queues and rate-limit
// namespaces, and its brand as Worker vars.
//
//   node scripts/pillcrow-client.mjs leon --d1-id <uuid> --name "LEON Mail" \
//     [--accent e63946] [--accent-dark ff8a94] [--icon-url https://…] \
//     [--background …] [--background-dark …] [--domain mail.leonband.uk]
//
// Writes wrangler.client-<slug>.jsonc (gitignored: it holds account ids) and prints the
// commands that create the resources and deploy.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { parseArgs } from "node:util";

const { values, positionals } = parseArgs({
	allowPositionals: true,
	options: {
		"d1-id": { type: "string" },
		name: { type: "string" },
		accent: { type: "string" },
		"accent-dark": { type: "string" },
		"icon-url": { type: "string" },
		background: { type: "string" },
		"background-dark": { type: "string" },
		domain: { type: "string" },
	},
});

const slug = positionals[0];
if (!slug || !/^[a-z0-9](?:[a-z0-9-]{0,30}[a-z0-9])?$/.test(slug)) {
	console.error("Usage: node scripts/pillcrow-client.mjs <slug> --d1-id <uuid> [--name …]\nThe slug is lowercase letters, digits and dashes, e.g. leon.");
	process.exit(1);
}

// wrangler.jsonc allows comments and trailing commas; strip both outside strings.
function parseJsonc(source) {
	let out = "";
	for (let i = 0; i < source.length; i++) {
		const ch = source[i];
		if (ch === '"') {
			let j = i + 1;
			while (j < source.length && source[j] !== '"') j += source[j] === "\\" ? 2 : 1;
			out += source.slice(i, j + 1);
			i = j;
		} else if (ch === "/" && source[i + 1] === "/") {
			while (i < source.length && source[i] !== "\n") i++;
			out += "\n";
		} else if (ch === "/" && source[i + 1] === "*") {
			i = source.indexOf("*/", i + 2) + 1;
		} else {
			out += ch;
		}
	}
	return JSON.parse(out.replace(/,(\s*[}\]])/g, "$1"));
}

const config = parseJsonc(readFileSync(new URL("../wrangler.jsonc", import.meta.url), "utf8"));
const worker = `mail-${slug}`;
const queue = (suffix) => `${worker}-${suffix}`;
const renameQueue = (name) => name.replace(/^mailflare-/, `${worker}-`);

config.name = worker;
config.services = config.services.map((service) =>
	service.binding === "WORKER_SELF_REFERENCE" ? { ...service, service: worker } : service,
);
config.d1_databases = config.d1_databases.map((db) => ({
	...db,
	database_name: worker,
	...(values["d1-id"] ? { database_id: values["d1-id"] } : {}),
}));
config.r2_buckets = config.r2_buckets.map((bucket) => ({ ...bucket, bucket_name: `${worker}-raw` }));
config.queues.producers = config.queues.producers.map((p) => ({ ...p, queue: renameQueue(p.queue) }));
config.queues.consumers = config.queues.consumers.map((c) => ({ ...c, queue: renameQueue(c.queue) }));

// Rate-limit namespaces are account-wide; give each install its own pair so one client's
// login attempts never count against another's.
const base = 10_000 + (parseInt(createHash("sha256").update(slug).digest("hex").slice(0, 8), 16) % 400_000) * 2;
config.ratelimits = config.ratelimits.map((limit, index) => ({ ...limit, namespace_id: String(base + index) }));

const vars = { CF_EMAIL_WORKER_NAME: worker };
const brand = {
	BRAND_NAME: values.name,
	BRAND_ICON_URL: values["icon-url"],
	BRAND_ACCENT: values.accent,
	BRAND_ACCENT_DARK: values["accent-dark"],
	BRAND_BACKGROUND: values.background,
	BRAND_BACKGROUND_DARK: values["background-dark"],
};
// Colours go in without "#": the app accepts both, and a bare hex survives dotenv tooling.
for (const [key, value] of Object.entries(brand)) {
	if (value) vars[key] = /^BRAND_(ACCENT|BACKGROUND)/.test(key) ? value.replace(/^#/, "") : value;
}
config.vars = { ...(config.vars ?? {}), ...vars };

if (values.domain) config.routes = [{ pattern: values.domain, custom_domain: true }];

const file = `wrangler.client-${slug}.jsonc`;
writeFileSync(new URL(`../${file}`, import.meta.url), `// Generated by scripts/pillcrow-client.mjs for "${slug}". Edit the flags and regenerate.\n${JSON.stringify(config, null, "\t")}\n`);

console.log(`Wrote ${file}.\n`);
if (!values["d1-id"]) {
	console.log("Create the resources first, then rerun with --d1-id:\n");
	console.log(`  npx wrangler d1 create ${worker}`);
	console.log(`  npx wrangler r2 bucket create ${worker}-raw`);
	for (const suffix of ["inbound", "outbound", "agent"]) console.log(`  npx wrangler queues create ${queue(suffix)}`);
	console.log("");
} else {
	console.log("Deploy, then set the runtime token:\n");
	console.log(`  WRANGLER_CONFIG=./${file} npm run deploy`);
	console.log(`  npx wrangler secret put CF_TOKEN --name ${worker}`);
	console.log(`\nThen open ${values.domain ? `https://${values.domain}` : `the ${worker} workers.dev URL`}/setup.`);
}
